using System.Collections.Generic;

public class Elemento
{
    public string Nome { get; set; }
    public List<int> DistribuicaoEletronica { get; set; }
    public string Curiosidade { get; set; } // Adicionado campo de curiosidade
}

public static class Table
{
    public static Dictionary<int, Elemento> Particles = new()
    {
        { 0, new Elemento { Nome = "Neutron", DistribuicaoEletronica = new List<int>(), Curiosidade = "Neutrons mantêm o núcleo estável." } },
        { 1, new Elemento { Nome = "Hidrogênio (H)", DistribuicaoEletronica = new List<int> { 1 }, Curiosidade = "É o elemento mais abundante do universo." } },
        { 2, new Elemento { Nome = "Hélio (He)", DistribuicaoEletronica = new List<int> { 2 }, Curiosidade = "Usado em balões por ser mais leve que o ar." } },
        { 3, new Elemento { Nome = "Lítio (Li)", DistribuicaoEletronica = new List<int> { 2, 1 }, Curiosidade = "Presente em baterias recarregáveis." } },
        { 4, new Elemento { Nome = "Berílio (Be)", DistribuicaoEletronica = new List<int> { 2, 2 }, Curiosidade = "Usado em janelas de raios X." } },
        { 5, new Elemento { Nome = "Boro (B)", DistribuicaoEletronica = new List<int> { 2, 3 }, Curiosidade = "Essencial para plantas." } },
        { 6, new Elemento { Nome = "Carbono (C)", DistribuicaoEletronica = new List<int> { 2, 4 }, Curiosidade = "Base da vida na Terra." } },
        { 7, new Elemento { Nome = "Nitrogênio (N)", DistribuicaoEletronica = new List<int> { 2, 5 }, Curiosidade = "Compõe 78% do ar atmosférico." } },
        { 8, new Elemento { Nome = "Oxigênio (O)", DistribuicaoEletronica = new List<int> { 2, 6 }, Curiosidade = "Essencial para respiração dos seres vivos." } },
        { 9, new Elemento { Nome = "Flúor (F)", DistribuicaoEletronica = new List<int> { 2, 7 }, Curiosidade = "Usado em cremes dentais." } },
        { 10, new Elemento { Nome = "Neônio (Ne)", DistribuicaoEletronica = new List<int> { 2, 8 }, Curiosidade = "Famoso por iluminar letreiros." } },
        { 11, new Elemento { Nome = "Sódio (Na)", DistribuicaoEletronica = new List<int> { 2, 8, 1 }, Curiosidade = "Presente no sal de cozinha." } },
        { 12, new Elemento { Nome = "Magnésio (Mg)", DistribuicaoEletronica = new List<int> { 2, 8, 2 }, Curiosidade = "Importante para músculos e ossos." } },
        { 13, new Elemento { Nome = "Alumínio (Al)", DistribuicaoEletronica = new List<int> { 2, 8, 3 }, Curiosidade = "Metal leve usado em latas." } },
        { 14, new Elemento { Nome = "Silício (Si)", DistribuicaoEletronica = new List<int> { 2, 8, 4 }, Curiosidade = "Base dos chips eletrônicos." } },
        { 15, new Elemento { Nome = "Fósforo (P)", DistribuicaoEletronica = new List<int> { 2, 8, 5 }, Curiosidade = "Presente em fósforos de caixa." } },
        { 16, new Elemento { Nome = "Enxofre (S)", DistribuicaoEletronica = new List<int> { 2, 8, 6 }, Curiosidade = "Responsável pelo cheiro de ovos podres." } },
        { 17, new Elemento { Nome = "Cloro (Cl)", DistribuicaoEletronica = new List<int> { 2, 8, 7 }, Curiosidade = "Usado para tratar água." } },
        { 18, new Elemento { Nome = "Argônio (Ar)", DistribuicaoEletronica = new List<int> { 2, 8, 8 }, Curiosidade = "Gás nobre usado em lâmpadas." } },
        { 19, new Elemento { Nome = "Potássio (K)", DistribuicaoEletronica = new List<int> { 2, 8, 8, 1 }, Curiosidade = "Essencial para o funcionamento dos nervos." } },
        { 20, new Elemento { Nome = "Cálcio (Ca)", DistribuicaoEletronica = new List<int> { 2, 8, 8, 2 }, Curiosidade = "Fundamental para ossos e dentes." } },
        { 21, new Elemento { Nome = "Escândio (Sc)", DistribuicaoEletronica = new List<int> { 2, 8, 9, 2 }, Curiosidade = "Usado em lâmpadas de alta intensidade." } },
        { 22, new Elemento { Nome = "Titânio (Ti)", DistribuicaoEletronica = new List<int> { 2, 8, 10, 2 }, Curiosidade = "Muito resistente e leve, usado em próteses." } },
        { 23, new Elemento { Nome = "Vanádio (V)", DistribuicaoEletronica = new List<int> { 2, 8, 11, 2 }, Curiosidade = "Usado para fortalecer aço." } },
        { 24, new Elemento { Nome = "Cromo (Cr)", DistribuicaoEletronica = new List<int> { 2, 8, 13, 1 }, Curiosidade = "Responsável pelo brilho do metal cromado." } },
        { 25, new Elemento { Nome = "Manganês (Mn)", DistribuicaoEletronica = new List<int> { 2, 8, 13, 2 }, Curiosidade = "Essencial para o metabolismo." } },
        { 26, new Elemento { Nome = "Ferro (Fe)", DistribuicaoEletronica = new List<int> { 2, 8, 14, 2 }, Curiosidade = "Presente no sangue, transporta oxigênio." } },
        { 27, new Elemento { Nome = "Cobalto (Co)", DistribuicaoEletronica = new List<int> { 2, 8, 15, 2 }, Curiosidade = "Usado em ímãs fortes." } },
        { 28, new Elemento { Nome = "Níquel (Ni)", DistribuicaoEletronica = new List<int> { 2, 8, 16, 2 }, Curiosidade = "Usado em moedas e baterias." } },
        { 29, new Elemento { Nome = "Cobre (Cu)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 1 }, Curiosidade = "Ótimo condutor de eletricidade." } },
        { 30, new Elemento { Nome = "Zinco (Zn)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 2 }, Curiosidade = "Usado para galvanizar ferro." } },
        { 31, new Elemento { Nome = "Gálio (Ga)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 3 }, Curiosidade = "Derrete na mão, ponto de fusão baixo." } },
        { 32, new Elemento { Nome = "Germânio (Ge)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 4 }, Curiosidade = "Usado em semicondutores." } },
        { 33, new Elemento { Nome = "Arsênio (As)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 5 }, Curiosidade = "Conhecido como veneno histórico." } },
        { 34, new Elemento { Nome = "Selênio (Se)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 6 }, Curiosidade = "Usado em fotocopiadoras." } },
        { 35, new Elemento { Nome = "Bromo (Br)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 7 }, Curiosidade = "Líquido à temperatura ambiente." } },
        { 36, new Elemento { Nome = "Criptônio (Kr)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 8 }, Curiosidade = "Usado em lâmpadas de flash." } },
        { 37, new Elemento { Nome = "Rubídio (Rb)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 8, 1 }, Curiosidade = "Usado em relógios atômicos." } },
        { 38, new Elemento { Nome = "Estrôncio (Sr)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 8, 2 }, Curiosidade = "Produz cor vermelha em fogos de artifício." } },
        { 39, new Elemento { Nome = "Ítrio (Y)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 9, 2 }, Curiosidade = "Usado em telas de LED." } },
        { 40, new Elemento { Nome = "Zircônio (Zr)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 10, 2 }, Curiosidade = "Resistente à corrosão, usado em reatores." } },
        { 41, new Elemento { Nome = "Nióbio (Nb)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 12, 1 }, Curiosidade = "Usado em supercondutores." } },
        { 42, new Elemento { Nome = "Molibdênio (Mo)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 13, 1 }, Curiosidade = "Essencial para enzimas." } },
        { 43, new Elemento { Nome = "Tecnécio (Tc)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 13, 2 }, Curiosidade = "Não ocorre naturalmente na Terra." } },
        { 44, new Elemento { Nome = "Rutênio (Ru)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 15, 1 }, Curiosidade = "Usado em contatos elétricos." } },
        { 45, new Elemento { Nome = "Ródio (Rh)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 16, 1 }, Curiosidade = "Muito usado em catalisadores automotivos." } },
        { 46, new Elemento { Nome = "Paládio (Pd)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 18 }, Curiosidade = "Absorve grandes quantidades de hidrogênio." } },
        { 47, new Elemento { Nome = "Prata (Ag)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 18, 1 }, Curiosidade = "Melhor condutor de eletricidade." } },
        { 48, new Elemento { Nome = "Cádmio (Cd)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 18, 2 }, Curiosidade = "Tóxico, usado em baterias." } },
        { 49, new Elemento { Nome = "Índio (In)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 18, 3 }, Curiosidade = "Usado em telas sensíveis ao toque." } },
        { 50, new Elemento { Nome = "Estanho (Sn)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 18, 4 }, Curiosidade = "Usado em soldas." } },
        { 51, new Elemento { Nome = "Antimônio (Sb)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 18, 5 }, Curiosidade = "Usado em chamas retardantes." } },
        { 52, new Elemento { Nome = "Telúrio (Te)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 18, 6 }, Curiosidade = "Usado em ligas metálicas." } },
        { 53, new Elemento { Nome = "Iodo (I)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 18, 7 }, Curiosidade = "Essencial para a tireoide." } },
        { 54, new Elemento { Nome = "Xenônio (Xe)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 18, 8 }, Curiosidade = "Usado em lâmpadas de flash e anestesia." } },
        { 55, new Elemento { Nome = "Césio (Cs)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 18, 8, 1 }, Curiosidade = "Altamente reativo com água." } },
        { 56, new Elemento { Nome = "Bário (Ba)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 18, 8, 2 }, Curiosidade = "Usado em exames de raio-X." } },
        { 57, new Elemento { Nome = "Lantânio (La)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 18, 9, 2 }, Curiosidade = "Usado em lentes de câmeras." } },
        { 58, new Elemento { Nome = "Cério (Ce)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 19, 9, 2 }, Curiosidade = "Usado em pedras de isqueiro." } },
        { 59, new Elemento { Nome = "Praseodímio (Pr)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 21, 8, 2 }, Curiosidade = "Usado em vidros verdes." } },
        { 60, new Elemento { Nome = "Neodímio (Nd)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 22, 8, 2 }, Curiosidade = "Usado em ímãs superpotentes." } },
        { 61, new Elemento { Nome = "Promécio (Pm)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 23, 8, 2 }, Curiosidade = "Não existe naturalmente, é radioativo." } },
        { 62, new Elemento { Nome = "Samário (Sm)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 24, 8, 2 }, Curiosidade = "Usado em ímãs e lasers." } },
        { 63, new Elemento { Nome = "Európio (Eu)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 25, 8, 2 }, Curiosidade = "Usado em telas de TV." } },
        { 64, new Elemento { Nome = "Gadolínio (Gd)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 25, 9, 2 }, Curiosidade = "Usado em exames de ressonância magnética." } },
        { 65, new Elemento { Nome = "Térbio (Tb)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 27, 8, 2 }, Curiosidade = "Usado em lâmpadas fluorescentes." } },
        { 66, new Elemento { Nome = "Disprósio (Dy)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 28, 8, 2 }, Curiosidade = "Usado em ímãs de alta resistência." } },
        { 67, new Elemento { Nome = "Hólmio (Ho)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 29, 8, 2 }, Curiosidade = "Tem forte magnetismo." } },
        { 68, new Elemento { Nome = "Érbio (Er)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 30, 8, 2 }, Curiosidade = "Usado em lasers médicos." } },
        { 69, new Elemento { Nome = "Túlio (Tm)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 31, 8, 2 }, Curiosidade = "Usado em equipamentos de raio-X portáteis." } },
        { 70, new Elemento { Nome = "Itérbio (Yb)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 8, 2 }, Curiosidade = "Usado em lasers de fibra óptica." } },
        { 71, new Elemento { Nome = "Lutécio (Lu)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 9, 2 }, Curiosidade = "O mais denso dos elementos terras raras." } },
        { 72, new Elemento { Nome = "Háfnio (Hf)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 10, 2 }, Curiosidade = "Usado em reatores nucleares." } },
        { 73, new Elemento { Nome = "Tântalo (Ta)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 11, 2 }, Curiosidade = "Resistente à corrosão, usado em eletrônicos." } },
        { 74, new Elemento { Nome = "Tungstênio (W)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 12, 2 }, Curiosidade = "Tem o maior ponto de fusão dos metais." } },
        { 75, new Elemento { Nome = "Rênio (Re)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 13, 2 }, Curiosidade = "Usado em motores a jato." } },
        { 76, new Elemento { Nome = "Ósmio (Os)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 14, 2 }, Curiosidade = "O metal mais denso conhecido." } },
        { 77, new Elemento { Nome = "Irídio (Ir)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 15, 2 }, Curiosidade = "Muito resistente à corrosão." } },
        { 78, new Elemento { Nome = "Platina (Pt)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 17, 1 }, Curiosidade = "Usada em joias e catalisadores." } },
        { 79, new Elemento { Nome = "Ouro (Au)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 18, 1 }, Curiosidade = "Muito valorizado desde a antiguidade." } },
        { 80, new Elemento { Nome = "Mercúrio (Hg)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 18, 2 }, Curiosidade = "Único metal líquido à temperatura ambiente." } },
        { 81, new Elemento { Nome = "Tálio (Tl)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 18, 3 }, Curiosidade = "Altamente tóxico." } },
        { 82, new Elemento { Nome = "Chumbo (Pb)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 18, 4 }, Curiosidade = "Usado em baterias e proteção contra radiação." } },
        { 83, new Elemento { Nome = "Bismuto (Bi)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 18, 5 }, Curiosidade = "Menos tóxico que outros metais pesados." } },
        { 84, new Elemento { Nome = "Polônio (Po)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 18, 6 }, Curiosidade = "Extremamente radioativo." } },
        { 85, new Elemento { Nome = "Astato (At)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 18, 7 }, Curiosidade = "Elemento mais raro da Terra." } },
        { 86, new Elemento { Nome = "Radônio (Rn)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 18, 8 }, Curiosidade = "Gás radioativo, pode se acumular em casas." } },
        { 87, new Elemento { Nome = "Frâncio (Fr)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 18, 8, 1 }, Curiosidade = "Extremamente raro e radioativo." } },
        { 88, new Elemento { Nome = "Rádio (Ra)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 18, 8, 2 }, Curiosidade = "Já foi usado em relógios luminosos." } },
        { 89, new Elemento { Nome = "Actínio (Ac)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 18, 9, 2 }, Curiosidade = "Brilha no escuro devido à radioatividade." } },
        { 90, new Elemento { Nome = "Tório (Th)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 18, 10, 2 }, Curiosidade = "Pode ser usado como combustível nuclear." } },
        { 91, new Elemento { Nome = "Protactínio (Pa)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 20, 9, 2 }, Curiosidade = "Muito raro e radioativo." } },
        { 92, new Elemento { Nome = "Urânio (U)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 21, 9, 2 }, Curiosidade = "Usado em energia nuclear." } },
        { 93, new Elemento { Nome = "Netúnio (Np)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 22, 9, 2 }, Curiosidade = "Produzido em reatores nucleares." } },
        { 94, new Elemento { Nome = "Plutônio (Pu)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 24, 8, 2 }, Curiosidade = "Usado em armas e energia nuclear." } },
        { 95, new Elemento { Nome = "Amerício (Am)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 25, 8, 2 }, Curiosidade = "Usado em detectores de fumaça." } },
        { 96, new Elemento { Nome = "Cúrio (Cm)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 25, 9, 2 }, Curiosidade = "Brilha no escuro devido à radioatividade." } },
        { 97, new Elemento { Nome = "Bérquio (Bk)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 27, 8, 2 }, Curiosidade = "Produzido artificialmente." } },
        { 98, new Elemento { Nome = "Califórnio (Cf)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 28, 8, 2 }, Curiosidade = "Usado para iniciar reatores nucleares." } },
        { 99, new Elemento { Nome = "Einstênio (Es)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 29, 8, 2 }, Curiosidade = "Descoberto após explosões nucleares." } },
        { 100, new Elemento { Nome = "Férmio (Fm)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 30, 8, 2 }, Curiosidade = "Produzido em testes nucleares." } },
        { 101, new Elemento { Nome = "Mendelévio (Md)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 31, 8, 2 }, Curiosidade = "Nomeado em homenagem a Mendeleev." } },
        { 102, new Elemento { Nome = "Nobélio (No)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 8, 2 }, Curiosidade = "Nomeado em homenagem a Nobel." } },
        { 103, new Elemento { Nome = "Laurêncio (Lr)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 9, 2 }, Curiosidade = "Último dos actinídeos." } },
        { 104, new Elemento { Nome = "Rutherfórdio (Rf)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 10, 2 }, Curiosidade = "Nomeado em homenagem a Rutherford." } },
        { 105, new Elemento { Nome = "Dúbnio (Db)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 11, 2 }, Curiosidade = "Produzido artificialmente." } },
        { 106, new Elemento { Nome = "Seabórgio (Sg)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 12, 2 }, Curiosidade = "Nomeado em homenagem a Seaborg." } },
        { 107, new Elemento { Nome = "Bóhrio (Bh)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 13, 2 }, Curiosidade = "Nomeado em homenagem a Bohr." } },
        { 108, new Elemento { Nome = "Hássio (Hs)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 14, 2 }, Curiosidade = "Produzido artificialmente." } },
        { 109, new Elemento { Nome = "Meitnério (Mt)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 15, 2 }, Curiosidade = "Nomeado em homenagem a Meitner." } },
        { 110, new Elemento { Nome = "Darmstádio (Ds)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 17, 1 }, Curiosidade = "Descoberto em Darmstadt, Alemanha." } },
        { 111, new Elemento { Nome = "Roentgênio (Rg)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 18, 1 }, Curiosidade = "Nomeado em homenagem a Roentgen." } },
        { 112, new Elemento { Nome = "Copernício (Cn)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 18, 2 }, Curiosidade = "Nomeado em homenagem a Copérnico." } },
        { 113, new Elemento { Nome = "Nihônio (Nh)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 18, 3 }, Curiosidade = "Descoberto no Japão." } },
        { 114, new Elemento { Nome = "Fleróvio (Fl)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 18, 4 }, Curiosidade = "Produzido artificialmente." } },
        { 115, new Elemento { Nome = "Moscóvio (Mc)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 18, 5 }, Curiosidade = "Nomeado em homenagem a Moscou." } },
        { 116, new Elemento { Nome = "Livermório (Lv)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 18, 6 }, Curiosidade = "Nomeado em homenagem a Livermore." } },
        { 117, new Elemento { Nome = "Tenessino (Ts)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 18, 7 }, Curiosidade = "Nomeado em homenagem ao Tennessee." } },
        { 118, new Elemento { Nome = "Oganessônio (Og)", DistribuicaoEletronica = new List<int> { 2, 8, 18, 32, 32, 18, 8 }, Curiosidade = "Elemento mais pesado conhecido." } },
    };
}